services:
  scanner:
    build: ./scanner
    container_name: secrets-scanner
    ports:
      - "8001:8001"
    networks:
      - secrets-net

  orchestrator:
    build: ./orchestrator
    container_name: secrets-orchestrator
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./test-repos:/repos:ro
      - scan_data:/app/data
    depends_on:
      - scanner
    networks:
      - secrets-net
  
  frontend:
    build: ./frontend
    container_name: secrets-frontend
    ports:
      - "5173:5173"
    depends_on:
      - orchestrator
    env_file:
      - .env
    networks:
      - secrets-net

networks:
  secrets-net:
    driver: bridge

volumes:
  scan_data:
